name = "StaticWebPages"
uuid = "5bf9d097-888b-4aa7-96b5-1bfe21b2dbad"
version = "0.2.23"
authors = ["azzaare <jf@baffier.fr>"]

[deps]
Bibliography = "f1be7e48-bf82-45af-a471-ae754a193061"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FTPClient = "01fcc997-4f28-56b8-8a06-30002c134abb"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"

[weakdeps]
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"

[extensions]
SWPGtkExtension = ["Gtk4"]

[compat]
Bibliography = "0.3"
DataStructures = "0.18, 0.19"
FTPClient = "1"
GitHub = "5"
Gtk4 = "0.3"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "ExplicitImports", "JET", "Test", "TestItemRunner"]
